t1 = ("a", "b", "c", "d", "", "f")
t2 = (1, 2, 3, 4, 5, 6, 9, 3, 2, 1, 2)

print(f"\nt1: {t1}")
print(f"t2: {t2}")

print(f"\nsum(t2): {sum(t2)}")
print(f"max(t1): {max(t1)}")
print(f"max(t2): {max(t2)}")
print(f"min(t1): {min(t1)}")
print(f"min(t2): {min(t2)}")
print(f"sorted(t1): {sorted(t1)}")
print(f"sorted(t2): {sorted(t2)}")
print(f"all(t1): {all(t1)}")
print(f"all(t2): {all(t2)}")
print(f"any(t1): {any(t1)}")
print(f"any(t2): {any(t2)}")
print(f"tuple(reversed(t1)): {tuple(reversed(t1))}")
print(f"tuple(reversed(t2)): {tuple(reversed(t2))}\n")